language: node_js

env:
     - DB=postgresql://postgres@localhost/user
node_js:
        - "v8.10.0"

before_script:

  - psql -c 'create database  user;' -U postgres
  - psql -U postgres -d user -a -f greetings.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2      