language: node_js

env:
     - DATABASE_URL=postgresql://postgres@localhost/user_counts

node_js:
        - "v8.10.0"

before_script:

  - psql -c 'create database user_counts;' -U postgres
  - psql -U postgres -d user_counts -a -f greetings.sql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2      